In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)

[1 2 3]
(3,)
int64
1


In [6]:
b = np.array([3,1,5])

In [7]:
c = a*b
c

array([ 3,  2, 15])

In [8]:
a1 = [1,2,3]
a2 = [2,3,4]

In [9]:
b1 = np.array(a1)
b2 = np.array(a2)

In [12]:
dot = np.dot(b1, b2)

In [13]:
dot

20

In [14]:
dot2 = b1 @ b2

In [15]:
dot2

20

In [16]:
a = np.random.randn(1000)

In [17]:
b = np.random.randn(1000)

In [20]:
dot3 = np.dot(a, b)

In [21]:
dot3

-11.557757748075883

In [44]:
array = np.array([[1,2,7], [4,5,16], [7,8,90]])

In [45]:
array

array([[ 1,  2,  7],
       [ 4,  5, 16],
       [ 7,  8, 90]])

In [25]:
array.shape

(2, 3)

In [26]:
array.dtype

dtype('int64')

In [35]:
print(array[0,0])

1


In [34]:
print(array[:,1])

[2 5 8]


In [33]:
print(array.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [39]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [38]:
a = np.array([[1,2], [3,4]])

In [46]:
np.linalg.inv(array)

array([[-1.65128205,  0.63589744,  0.01538462],
       [ 1.27179487, -0.21025641, -0.06153846],
       [ 0.01538462, -0.03076923,  0.01538462]])

In [47]:
d = np.diag(array)

In [48]:
d

array([ 1,  5, 90])

In [49]:
e = np.diag(d)

In [50]:
e

array([[ 1,  0,  0],
       [ 0,  5,  0],
       [ 0,  0, 90]])

In [51]:
bool_index = array > 5
bool_index

array([[False, False,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [52]:
print(array[bool_index])

[ 7 16  7  8 90]


In [53]:
new = np.where(array > 5, array, -99)

In [54]:
new

array([[-99, -99,   7],
       [-99, -99,  16],
       [  7,   8,  90]])

In [60]:
a = np.random.randint(10, size = 10)
a

array([4, 8, 4, 2, 1, 3, 2, 7, 7, 6])

In [62]:
b = np.random.randint(10, size =3)
b

array([2, 9, 0])

In [63]:
c = a[b]

In [64]:
c

array([4, 6, 4])

In [75]:
a = np.random.randint(100, size=20)
a

array([ 6, 44, 91, 83, 97, 67, 43, 82, 14, 59, 14, 64, 32, 22, 18, 62,  0,
        6, 72, 45])

In [80]:
even = np.argwhere(a%2==0).flatten()

In [81]:
even

array([ 0,  1,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [82]:
print(a[even])

[ 6 44 82 14 14 64 32 22 18 62  0  6 72]


In [83]:
dict_a = {'a': 1, 'b': 20, 'c': 33}
dict_b = {'d': 11, 'b': 21, 'e': 0}
z = dict_a|dict_b

TypeError: unsupported operand type(s) for |: 'dict' and 'dict'