In [2]:
#Human Cyborg Relations
import numpy as np

In [4]:
set_a = np.random.randint(0, 101, 10)
set_b = np.random.randint(0, 101, 10)
print(set_a)
print(...)
print(set_b)
print(...)
print(set_a*set_b)

[78  5 91 68 10  1 67 75 91 23]
Ellipsis
[32 84 74 41  1 90 47 13 82 18]
Ellipsis
[2496  420 6734 2788   10   90 3149  975 7462  414]


In [5]:
print(...) # Code is cool.
print("...")

Ellipsis
...
